name: rinze
description: Rinze Laundry App
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  timeline_tile: ^2.0.0
  http: ^1.2.2
  flutter_dotenv: ^5.2.1
  flutter_secure_storage: ^9.2.2
  provider: ^6.1.2
  flutter_local_notifications: ^18.0.0
  permission_handler: ^11.3.1
  location: ^7.0.1
  geocoding: ^3.0.0
  intl: ^0.19.0
  sleek_circular_slider: ^2.0.1
  vibration: ^2.0.1
  shimmer: ^2.0.0
  image_picker: ^0.8.4+4
  socket_io_client: ^3.0.2
  shared_preferences: ^2.3.3
  url_launcher: ^6.3.1
  page_transition: ^2.1.0 
  razorpay_flutter: ^1.3.7
  smooth_page_indicator: ^1.2.0+3
  pdf: ^3.8.1
  flutter_downloader: ^1.12.0
  path_provider: ^2.0.11
  share_plus: ^7.0.0
  flutter_image: ^4.1.11
  scratcher: ^2.5.0
  animated_rating_stars: ^1.0.1

dev_dependencies:
  flutter_launcher_icons: ^0.10.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/images/
    - assets/icons/
    - .env
  uses-material-design: true
  fonts:
    - family: PlusJakartaSans
      fonts:
        - asset: fonts/PlusJakartaSans.ttf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/rinze_logo_1024sq.png"
